language: php

sudo: true

dist: trusty

services:
  - mysql

addons:
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.0
  - 7.1
  - 7.2

env:
  fast_finish: true
  matrix:
    - DB=pgsql    MOODLE_BRANCH=MOODLE_35_STABLE
    - DB=mysqli   MOODLE_BRANCH=MOODLE_35_STABLE

    - DB=pgsql    MOODLE_BRANCH=MOODLE_36_STABLE
    - DB=mysqli   MOODLE_BRANCH=MOODLE_36_STABLE

    - DB=pgsql    MOODLE_BRANCH=MOODLE_37_STABLE
    - DB=mysqli   MOODLE_BRANCH=MOODLE_37_STABLE

    - DB=pgsql    MOODLE_BRANCH=master
    - DB=mysqli   MOODLE_BRANCH=master

  allow_failures:
    - DB=pgsql    MOODLE_BRANCH=master
    - DB=mysqli   MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

jobs:
  include:
    # Prechecks against latest Moodle stable only. Testing against PHP 7.0, 7.1 and 7.2.
    # pgsql
    - stage: develop
      php: 7.0
      env: DB=pgsql    MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/script.sh

    - stage: develop
      php: 7.1
      env: DB=pgsql    MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/script.sh

    - stage: develop
      php: 7.2
      env: DB=pgsql    MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/script.sh

    # mysql
    - stage: develop
      php: 7.0
      env: DB=mysqli   MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/script.sh

    - stage: develop
      php: 7.1
      env: DB=mysqli   MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/script.sh

    - stage: develop
      php: 7.2
      env: DB=mysqli   MOODLE_BRANCH=MOODLE_37_STABLE
      install:
        - moodle-plugin-ci install
      script:
        - bash $TRAVIS_BUILD_DIR/.travis/script.sh

# Default 'test' stage: All tests against full matrix.
install:
  - moodle-plugin-ci install
script:
  - bash $TRAVIS_BUILD_DIR/.travis/script.sh

after_success:
  - moodle-plugin-ci coveralls-upload

stages:
  - name: develop
    if: branch != master
  - name: test
    if: branch = master